export interface CapagSeedEntry {
  municipalityIbgeCode: string;
  municipalityName: string;
  uf: string;
  capagRating: 'A' | 'B' | 'C' | 'ND';
}

export const CAPAG_SEED_DATA: CapagSeedEntry[] = [
  { municipalityIbgeCode: '3550308', municipalityName: 'São Paulo', uf: 'SP', capagRating: 'A' },
  { municipalityIbgeCode: '3304557', municipalityName: 'Rio de Janeiro', uf: 'RJ', capagRating: 'B' },
  { municipalityIbgeCode: '5300108', municipalityName: 'Brasília', uf: 'DF', capagRating: 'A' },
  { municipalityIbgeCode: '3106200', municipalityName: 'Belo Horizonte', uf: 'MG', capagRating: 'B' },
  { municipalityIbgeCode: '2927408', municipalityName: 'Salvador', uf: 'BA', capagRating: 'C' },
  { municipalityIbgeCode: '2304400', municipalityName: 'Fortaleza', uf: 'CE', capagRating: 'B' },
  { municipalityIbgeCode: '4106902', municipalityName: 'Curitiba', uf: 'PR', capagRating: 'A' },
  { municipalityIbgeCode: '1302603', municipalityName: 'Manaus', uf: 'AM', capagRating: 'C' },
  { municipalityIbgeCode: '2611606', municipalityName: 'Recife', uf: 'PE', capagRating: 'B' },
  { municipalityIbgeCode: '4314902', municipalityName: 'Porto Alegre', uf: 'RS', capagRating: 'A' },
  { municipalityIbgeCode: '1501402', municipalityName: 'Belém', uf: 'PA', capagRating: 'C' },
  { municipalityIbgeCode: '5208707', municipalityName: 'Goiânia', uf: 'GO', capagRating: 'A' },
  { municipalityIbgeCode: '4205407', municipalityName: 'Florianópolis', uf: 'SC', capagRating: 'A' },
  { municipalityIbgeCode: '2111300', municipalityName: 'São Luís', uf: 'MA', capagRating: 'C' },
  { municipalityIbgeCode: '2704302', municipalityName: 'Maceió', uf: 'AL', capagRating: 'B' },
  { municipalityIbgeCode: '2408102', municipalityName: 'Natal', uf: 'RN', capagRating: 'B' },
  { municipalityIbgeCode: '2211001', municipalityName: 'Teresina', uf: 'PI', capagRating: 'C' },
  { municipalityIbgeCode: '5002704', municipalityName: 'Campo Grande', uf: 'MS', capagRating: 'A' },
  { municipalityIbgeCode: '2507507', municipalityName: 'João Pessoa', uf: 'PB', capagRating: 'C' },
  { municipalityIbgeCode: '2800308', municipalityName: 'Aracaju', uf: 'SE', capagRating: 'B' },
  { municipalityIbgeCode: '5103403', municipalityName: 'Cuiabá', uf: 'MT', capagRating: 'C' },
  { municipalityIbgeCode: '1100205', municipalityName: 'Porto Velho', uf: 'RO', capagRating: 'ND' },
  { municipalityIbgeCode: '1600303', municipalityName: 'Macapá', uf: 'AP', capagRating: 'ND' },
  { municipalityIbgeCode: '1200401', municipalityName: 'Rio Branco', uf: 'AC', capagRating: 'ND' },
  { municipalityIbgeCode: '1400100', municipalityName: 'Boa Vista', uf: 'RR', capagRating: 'ND' },
  { municipalityIbgeCode: '1721000', municipalityName: 'Palmas', uf: 'TO', capagRating: 'B' },
  { municipalityIbgeCode: '3205309', municipalityName: 'Vitória', uf: 'ES', capagRating: 'A' },
  { municipalityIbgeCode: '3304904', municipalityName: 'São Gonçalo', uf: 'RJ', capagRating: 'C' },
  { municipalityIbgeCode: '3301702', municipalityName: 'Duque de Caxias', uf: 'RJ', capagRating: 'C' },
  { municipalityIbgeCode: '3303500', municipalityName: 'Nova Iguaçu', uf: 'RJ', capagRating: 'C' },
  { municipalityIbgeCode: '3518800', municipalityName: 'Guarulhos', uf: 'SP', capagRating: 'B' },
  { municipalityIbgeCode: '3509502', municipalityName: 'Campinas', uf: 'SP', capagRating: 'A' },
  { municipalityIbgeCode: '3548708', municipalityName: 'São Bernardo do Campo', uf: 'SP', capagRating: 'A' },
  { municipalityIbgeCode: '3547809', municipalityName: 'Santo André', uf: 'SP', capagRating: 'B' },
  { municipalityIbgeCode: '3534401', municipalityName: 'Osasco', uf: 'SP', capagRating: 'B' },
  { municipalityIbgeCode: '3543402', municipalityName: 'Ribeirão Preto', uf: 'SP', capagRating: 'A' },
  { municipalityIbgeCode: '3552205', municipalityName: 'Sorocaba', uf: 'SP', capagRating: 'B' },
  { municipalityIbgeCode: '3548500', municipalityName: 'Santos', uf: 'SP', capagRating: 'B' },
  { municipalityIbgeCode: '3549904', municipalityName: 'São José dos Campos', uf: 'SP', capagRating: 'A' },
  { municipalityIbgeCode: '3530607', municipalityName: 'Mogi das Cruzes', uf: 'SP', capagRating: 'B' },
  { municipalityIbgeCode: '3118601', municipalityName: 'Contagem', uf: 'MG', capagRating: 'B' },
  { municipalityIbgeCode: '3170206', municipalityName: 'Uberlândia', uf: 'MG', capagRating: 'B' },
  { municipalityIbgeCode: '3303302', municipalityName: 'Niterói', uf: 'RJ', capagRating: 'B' },
  { municipalityIbgeCode: '2910800', municipalityName: 'Feira de Santana', uf: 'BA', capagRating: 'C' },
  { municipalityIbgeCode: '5201405', municipalityName: 'Aparecida de Goiânia', uf: 'GO', capagRating: 'ND' },
  { municipalityIbgeCode: '4209102', municipalityName: 'Joinville', uf: 'SC', capagRating: 'A' },
  { municipalityIbgeCode: '4113700', municipalityName: 'Londrina', uf: 'PR', capagRating: 'B' },
  { municipalityIbgeCode: '4115200', municipalityName: 'Maringá', uf: 'PR', capagRating: 'A' },
  { municipalityIbgeCode: '1500800', municipalityName: 'Ananindeua', uf: 'PA', capagRating: 'ND' },
  { municipalityIbgeCode: '3106705', municipalityName: 'Betim', uf: 'MG', capagRating: 'B' },
];
